var items = [
				"<option value='all_items'>全部道具</option>",
				"<option value='res_gold_5'>5金币</option>",
				"<option value='res_gold_10'>10金币</option>",
				"<option value='res_gold_20'>20金币</option>",
				"<option value='res_gold_50'>50金币</option>",
				"<option value='res_gold_100'>100金币</option>",
				"<option value='res_gold_200'>200金币</option>",
				"<option value='res_gold_500'>500金币</option>",
				"<option value='res_gold_1K'>1K金币</option>",
				"<option value='res_gold_2K'>2K金币</option>",
				"<option value='res_gold_5K'>5K金币</option>",
				"<option value='res_gold_10K'>10K金币</option>",
				"<option value='res_food_1K'>1K食品</option>",
				"<option value='res_food_2K'>2K食品</option>",
				"<option value='res_food_5K'>5K食品</option>",
				"<option value='res_food_10K'>10K食品</option>",
				"<option value='res_food_50K'>50K食品</option>",
				"<option value='res_food_100K'>100K食品</option>",
				"<option value='res_food_250K'>250K食品</option>",
				"<option value='res_food_500K'>500K食品</option>",
				"<option value='res_food_1M'>1M食品</option>",
				"<option value='res_food_2.5M'>2.5M食品</option>",
				"<option value='res_food_5M'>5M食品</option>",
				"<option value='res_metal_1K'>1K金属</option>",
				"<option value='res_metal_2K'>2K金属</option>",
				"<option value='res_metal_5K'>5K金属</option>",
				"<option value='res_metal_10K'>10K金属</option>",
				"<option value='res_metal_50K'>50K金属</option>",
				"<option value='res_metal_100K'>100K金属</option>",
				"<option value='res_metal_250K'>250K金属</option>",
				"<option value='res_metal_500K'>500K金属</option>",
				"<option value='res_metal_1M'>1M金属</option>",
				"<option value='res_metal_2.5M'>2.5M金属</option>",
				"<option value='res_metal_5M'>5M金属</option>",
				"<option value='res_oil_200'>200石油</option>",
				"<option value='res_oil_400'>400石油</option>",
				"<option value='res_oil_1.2K'>1.2K石油</option>",
				"<option value='res_oil_2.4K'>2.4K石油</option>",
				"<option value='res_oil_12K'>12K石油</option>",
				"<option value='res_oil_24K'>24K石油</option>",
				"<option value='res_oil_60K'>60K石油</option>",
				"<option value='res_oil_120K'>120K石油</option>",
				"<option value='res_oil_240K'>240K石油</option>",
				"<option value='res_oil_600K'>600K石油</option>",
				"<option value='res_oil_1.2M'>1.2M石油</option>",
				"<option value='res_alloy_50'>50合金</option>",
				"<option value='res_alloy_100'>100合金</option>",
				"<option value='res_alloy_300'>300合金</option>",
				"<option value='res_alloy_600'>600合金</option>",
				"<option value='res_alloy_3K'>3K合金</option>",
				"<option value='res_alloy_6K'>6K合金</option>",
				"<option value='res_alloy_15K'>15K合金</option>",
				"<option value='res_alloy_30K'>30K合金</option>",
				"<option value='res_alloy_60K'>60K合金</option>",
				"<option value='res_alloy_150K'>150K合金</option>",
				"<option value='res_alloy_300K'>300K合金</option>",
				"<option value='add_gem_1'>1金筹码</option>",
				"<option value='add_gem_2'>2金筹码</option>",
				"<option value='add_gem_3'>3金筹码</option>",
				"<option value='add_gem_5'>5金筹码</option>",
				"<option value='add_gem_10'>10金筹码</option>",
				"<option value='add_gem_20'>20金筹码</option>",
				"<option value='add_gem_50'>50金筹码</option>",
				"<option value='add_gem_100'>100金筹码</option>",
				"<option value='add_gem_200'>200金筹码</option>",
				"<option value='add_gem_500'>500金筹码</option>",
				"<option value='add_gem_1K'>1K金筹码</option>",
				"<option value='add_copper_1000'>1K银筹码</option>",
				"<option value='add_copper_1500'>1.5K银筹码</option>",
				"<option value='add_copper_3000'>3K银筹码</option>",
				"<option value='add_copper_5000'>5K银筹码</option>",
				"<option value='add_copper_10k'>10K银筹码</option>",
				"<option value='add_copper_50k'>50K银筹码</option>",
				"<option value='add_copper_100k'>100K银筹码</option>",
				"<option value='add_silver_100'>100银币</option>",
				"<option value='add_silver_300'>300银币</option>",
				"<option value='add_silver_500'>500银币</option>",
				"<option value='add_silver_1K'>1K银币</option>",
				"<option value='add_silver_5K'>5K银币</option>",
				"<option value='add_silver_10K'>10K银币</option>",
				"<option value='add_silver_50K'>50K银币</option>",
				"<option value='add_silver_100K'>100K银币</option>",
				"<option value='add_silver_500K'>500K银币</option>",
				"<option value='add_silver_1M'>1M银币</option>",
				"<option value='res_khorium_100'>100氪晶</option>",
				"<option value='res_khorium_300'>300氪晶</option>",
				"<option value='res_khorium_500'>500氪晶</option>",
				"<option value='res_khorium_1K'>1K氪晶</option>",
				"<option value='res_khorium_5K'>5K氪晶</option>",
				"<option value='res_khorium_10K'>10K氪晶</option>",
				"<option value='res_khorium_50K'>50K氪晶</option>",
				"<option value='vip_30M'>VIP 30M</option>",
				"<option value='vip_1H'>VIP 1H</option>",
				"<option value='vip_1D'>VIP 1D</option>",
				"<option value='vip_3D'>VIP 3D</option>",
				"<option value='vip_7D'>VIP 7D</option>",
				"<option value='vip_15D'>VIP 15D</option>",
				"<option value='vip_30D'>VIP 30D</option>",
				"<option value='vip_10P'>10 VIP点数</option>",
				"<option value='vip_100P'>100 VIP点数</option>",
				"<option value='vip_300P'>300 VIP点数</option>",
				"<option value='vip_500P'>500 VIP点数</option>",
				"<option value='vip_1000P'>1K VIP点数</option>",
				"<option value='vip_5K'>5K VIP点数</option>",
				"<option value='vip_10K'>10K VIP点数</option>",
				"<option value='vip_50K'>50K VIP点数</option>",
				"<option value='vip_100K'>100K VIP点数</option>",
				"<option value='acc_1M'>1M加速</option>",
				"<option value='acc_5M'>5M加速</option>",
				"<option value='acc_15M'>15M加速</option>",
				"<option value='acc_30M'>30M加速</option>",
				"<option value='acc_1H'>1H加速</option>",
				"<option value='acc_3H'>3H加速</option>",
				"<option value='acc_6H'>6H加速</option>",
				"<option value='acc_12H'>12H加速</option>",
				"<option value='acc_24H'>24H加速</option>",
				"<option value='build_acc_1M'>1M建造加速</option>",
				"<option value='build_acc_5M'>5M建造加速</option>",
				"<option value='build_acc_15M'>15M建造加速</option>",
				"<option value='build_acc_30M'>30M建造加速</option>",
				"<option value='build_acc_1H'>1H建造加速</option>",
				"<option value='build_acc_3H'>3H建造加速</option>",
				"<option value='build_acc_6H'>6H建造加速</option>",
				"<option value='build_acc_12H'>12H建造加速</option>",
				"<option value='build_acc_24H'>24H建造加速</option>",
				"<option value='science_acc_1M'>1M研究加速</option>",
				"<option value='science_acc_5M'>5M研究加速</option>",
				"<option value='science_acc_15M'>15M研究加速</option>",
				"<option value='science_acc_30M'>30M研究加速</option>",
				"<option value='science_acc_1H'>1H研究加速</option>",
				"<option value='science_acc_3H'>3H研究加速</option>",
				"<option value='science_acc_6H'>6H研究加速</option>",
				"<option value='science_acc_12H'>12H研究加速</option>",
				"<option value='science_acc_24H'>24H研究加速</option>",
				"<option value='produce_acc_1M'>1M生产加速</option>",
				"<option value='produce_acc_5M'>5M生产加速</option>",
				"<option value='produce_acc_15M'>15M生产加速</option>",
				"<option value='produce_acc_30M'>30M生产加速</option>",
				"<option value='produce_acc_1H'>1H生产加速</option>",
				"<option value='produce_acc_3H'>3H生产加速</option>",
				"<option value='produce_acc_6H'>6H生产加速</option>",
				"<option value='produce_acc_12H'>12H生产加速</option>",
				"<option value='produce_acc_24H'>24H生产加速</option>",
				"<option value='heal_acc_1M'>1M维修加速</option>",
				"<option value='heal_acc_5M'>5M维修加速</option>",
				"<option value='heal_acc_15M'>15M维修加速</option>",
				"<option value='heal_acc_30M'>30M维修加速</option>",
				"<option value='heal_acc_1H'>1H维修加速</option>",
				"<option value='heal_acc_3H'>3H维修加速</option>",
				"<option value='heal_acc_6H'>6H维修加速</option>",
				"<option value='heal_acc_12H'>12H维修加速</option>",
				"<option value='heal_acc_24H'>24H维修加速</option>",
				"<option value='foring_acc_1M'>1M强化加速</option>",
				"<option value='foring_acc_5M'>5M强化加速</option>",
				"<option value='foring_acc_15M'>15M强化加速</option>",
				"<option value='foring_acc_30M'>30M强化加速</option>",
				"<option value='foring_acc_1H'>1H强化加速</option>",
				"<option value='foring_acc_3H'>3H强化加速</option>",
				"<option value='foring_acc_6H'>6H强化加速</option>",
				"<option value='foring_acc_12H'>12H强化加速</option>",
				"<option value='foring_acc_24H'>24H强化加速</option>",
				"<option value='add_userEXP_100'>100指挥官经验</option>",
				"<option value='add_userEXP_500'>500指挥官经验</option>",
				"<option value='add_userEXP_1K'>1K指挥官经验</option>",
				"<option value='add_userEXP_2K'>2k指挥官经验</option>",
				"<option value='add_userEXP_5K'>5k指挥官经验</option>",
				"<option value='add_userEXP_10K'>10k指挥官经验</option>",
				"<option value='add_userEXP_50K'>50k指挥官经验</option>",
				"<option value='add_userEXP_100K'>100k指挥官经验</option>",
				"<option value='add_userEXP_500K'>500k指挥官经验</option>",
				"<option value='add_physicalStrength_10'>10体力</option>",
				"<option value='add_physicalStrength_30'>30体力</option>",
				"<option value='add_physicalStrength_50'>50体力</option>",
				"<option value='add_physicalStrength_100'>100体力</option>",
				"<option value='troops_limit_4H'>4H出征提升</option>",
				"<option value='troops_limit_8H'>8H出征提升</option>",
				"<option value='troops_limit_12H'>12H出征提升</option>",
				"<option value='troops_limit_24H'>24H出征提升</option>",
				"<option value='atk_add_6H'>6H火力提升</option>",
				"<option value='atk_add_12H'>12H火力提升</option>",
				"<option value='atk_add_24H'>24H火力提升</option>",
				"<option value='atk_add_3D'>3D火力提升</option>",
				"<option value='atk_add_7D'>7D火力提升</option>",
				"<option value='def_add_6H'>6H防御提升</option>",
				"<option value='def_add_12H'>12H防御提升</option>",
				"<option value='def_add_24H'>24H防御提升</option>",
				"<option value='def_add_3D'>3D防御提升</option>",
				"<option value='def_add_7D'>7D防御提升</option>",
				"<option value='food_consume25P_red_24H'>初级军费缩减24H</option>",
				"<option value='food_consume25P_red_3D'>初级军费缩减3D</option>",
				"<option value='food_consume25P_red_5D'>初级军费缩减5D</option>",
				"<option value='food_consume50P_red_24H'>高级军费缩减24H</option>",
				"<option value='food_consume50P_red_3D'>高级军费缩减3D</option>",
				"<option value='food_consume50P_red_5D'>高级军费缩减5D</option>",
				"<option value='food_produce_add'>食品厂增产</option>",
				"<option value='metal_produce_add'>冶炼厂增产</option>",
				"<option value='oil_produce_add'>炼油厂增产</option>",
				"<option value='alloy_produce_add'>合金厂增产</option>",
				"<option value='collectSpeed_8H'>8H采集加速</option>",
				"<option value='collectSpeed_24H'>24H采集加速</option>",
				"<option value='war_protect_1H'>1H战争保护</option>",
				"<option value='war_protect_8H'>8H战争保护</option>",
				"<option value='war_protect_24H'>24H战争保护</option>",
				"<option value='war_protect_3D'>3D战争保护</option>",
				"<option value='war_protect_7D'>7D战争保护</option>",
				"<option value='ati_spy_24H'>24H侦察干扰</option>",
				"<option value='ati_spy_3D'>3D侦察干扰</option>",
				"<option value='ati_spy_7D'>7D侦察干扰</option>",
				"<option value='camouflage_24H'>24H部队克隆</option>",
				"<option value='camouflage_3D'>3D部队克隆</option>",
				"<option value='camouflage_7D'>7D部队克隆</option>",
				"<option value='march_acc_100P'>普通行军加速100%</option>",
				"<option value='march_acc_50P'>普通行军加速50%</option>",
				"<option value='march_acc_25P'>普通行军加速25%</option>",
				"<option value='march_acc_100P_high'>高级行军加速100%</option>",
				"<option value='march_acc_50P_high'>高级行军加速50%</option>",
				"<option value='march_acc_25P_high'>高级行军加速25%</option>",
				"<option value='recall_troops_low'>普通部署召回</option>",
				"<option value='recall_troops_high'>高级部署召回</option>",
				"<option value='add_queue_8H'>8H工程队</option>",
				"<option value='add_queue_1D'>1D工程队</option>",
				"<option value='add_queue_3D'>3D工程队</option>",
				"<option value='add_queue_7D'>7D工程队</option>",
				"<option value='userSkill_resetting'>技能重置卡</option>",
				"<option value='userArmy_resetting'>兵种重置卡</option>",
				"<option value='modify_userName'>指挥官改名卡</option>",
				"<option value='modify_userImage'>指挥官形象</option>",
				"<option value='notice_horn'>大喇叭</option>",
				"<option value='move_build'>建筑移动</option>",
				"<option value='reinforce_wall'>城墙完全修复</option>",
				"<option value='LvUp_steel'>钢筋</option>",
				"<option value='allianceLicence'>联盟协议</option>",
				"<option value='copy_resetting'>遗迹重置卡</option>",
				"<option value='box_611'>普通材料补给箱</option>",
				"<option value='box_652'>精良材料补给箱</option>",
				"<option value='box_6103'>罕见材料补给箱</option>",
				"<option value='box_6154'>稀有材料补给箱</option>",
				"<option value='box_6205'>专家材料补给箱</option>",
				"<option value='box_411'>普通强化材料箱</option>",
				"<option value='box_452'>精良强化材料箱</option>",
				"<option value='box_4103'>罕见强化材料箱</option>",
				"<option value='box_4154'>稀有强化材料箱</option>",
				"<option value='box_4205'>专家强化材料箱</option>",
				"<option value='box_511'>普通重铸材料箱</option>",
				"<option value='box_552'>精良重铸材料箱</option>",
				"<option value='box_5103'>罕见重铸材料箱</option>",
				"<option value='box_5154'>稀有重铸材料箱</option>",
				"<option value='box_5205'>专家重铸材料箱</option>",
				"<option value='box_811'>普通图纸箱</option>",
				"<option value='box_852'>精良图纸箱</option>",
				"<option value='box_8103'>罕见图纸箱</option>",
				"<option value='box_8154'>稀有图纸箱</option>",
				"<option value='box_8205'>专家图纸箱</option>",
				"<option value='box_741'>普通装备箱</option>",
				"<option value='box_742'>精良装备箱</option>",
				"<option value='box_743'>罕见装备箱</option>",
				"<option value='box_744'>稀有装备箱</option>",
				"<option value='box_745'>专家装备箱</option>",
				"<option value='box_1011'>小型加速补给箱</option>",
				"<option value='box_1022'>中型加速补给箱</option>",
				"<option value='box_1033'>大型加速补给箱</option>",
				"<option value='box_1044'>超级加速补给箱</option>",
				"<option value='box_912'>火速进攻补给箱</option>",
				"<option value='box_924'>防守反击补给箱</option>",
				"<option value='box_932'>完美隐匿补给箱</option>",
				"<option value='box_944'>特殊资源补给箱</option>",
				"<option value='box_312'>小型资源集装箱</option>",
				"<option value='box_353'>中型资源集装箱</option>",
				"<option value='box_3104'>大型资源集装箱</option>",
				"<option value='box_3155'>超级资源集装箱</option>",
				"<option value='box_151'>5级补给箱</option>",
				"<option value='box_161'>6级补给箱</option>",
				"<option value='box_171'>7级补给箱</option>",
				"<option value='box_181'>8级补给箱</option>",
				"<option value='box_191'>9级补给箱</option>",
				"<option value='box_1101'>10级补给箱</option>",
				"<option value='box_1111'>11级补给箱</option>",
				"<option value='box_1121'>12级补给箱</option>",
				"<option value='box_1131'>13级补给箱</option>",
				"<option value='box_1141'>14级补给箱</option>",
				"<option value='box_1151'>15级补给箱</option>",
				"<option value='box_1161'>16级补给箱</option>",
				"<option value='box_1171'>17级补给箱</option>",
				"<option value='box_1181'>18级补给箱</option>",
				"<option value='box_1191'>19级补给箱</option>",
				"<option value='box_1201'>20级补给箱</option>",
				"<option value='box_100_1'>新服预约礼包</option>",
				"<option value='box_100_2'>5星好评礼包</option>",
				"<option value='box_100_3'>论坛热评礼包</option>",
				"<option value='box_100_4'>微博互动礼包</option>",
				"<option value='box_100_5'>官方开服礼包</option>",
				"<option value='box_100_6'>节日通用礼包</option>",
				"<option value='box_100_7'>平台通用礼包</option>",
				"<option value='box_99_1_5_1'>新服礼盒</option>",
				"<option value='box_99_1_5_2'>闪电战加速箱</option>",
				"<option value='box_99_1_5_3'>稀有资源箱</option>",
	        ];
var equips = [
				"<option value='all_equips'>全部装备</option>",
				"<option value='Equip_1_4_1_1'>4级：突击步枪</option>",
				"<option value='Equip_1_4_2_1'>4级：迷彩装</option>",
				"<option value='Equip_1_5_3_1'>5级：钢盔</option>",
				"<option value='Equip_1_5_4_1'>5级：防滑手套</option>",
				"<option value='Equip_1_6_5_1'>6级：军靴</option>",
				"<option value='Equip_1_6_6_1'>6级：护目镜</option>",
				"<option value='Equip_1_7_7_1'>7级：数字指南针 </option>",
				"<option value='Equip_1_7_8_1'>7级：勇士勋章</option>",
				"<option value='Equip_1_9_1_2'>9级：突击步枪</option>",
				"<option value='Equip_1_9_2_2'>9级：迷彩装</option>",
				"<option value='Equip_1_10_3_2'>10级：钢盔</option>",
				"<option value='Equip_1_10_4_2'>10级：防滑手套</option>",
				"<option value='Equip_1_11_5_2'>11级：军靴</option>",
				"<option value='Equip_1_11_6_2'>11级：护目镜</option>",
				"<option value='Equip_1_12_7_2'>12级：数字指南针 </option>",
				"<option value='Equip_1_12_8_2'>12级：勇士勋章</option>",
				"<option value='Equip_1_14_1_3'>14级：突击步枪</option>",
				"<option value='Equip_1_14_2_3'>14级：迷彩装</option>",
				"<option value='Equip_1_15_3_3'>15级：钢盔</option>",
				"<option value='Equip_1_15_4_3'>15级：防滑手套</option>",
				"<option value='Equip_1_16_5_3'>16级：军靴</option>",
				"<option value='Equip_1_16_6_3'>16级：护目镜</option>",
				"<option value='Equip_1_17_7_3'>17级：数字指南针 </option>",
				"<option value='Equip_1_17_8_3'>17级：勇士勋章</option>",
				"<option value='Equip_1_19_1_4'>19级：突击步枪</option>",
				"<option value='Equip_1_19_2_4'>19级：迷彩装</option>",
				"<option value='Equip_1_20_3_4'>20级：钢盔</option>",
				"<option value='Equip_1_20_4_4'>20级：防滑手套</option>",
				"<option value='Equip_1_21_5_4'>21级：军靴</option>",
				"<option value='Equip_1_21_6_4'>21级：护目镜</option>",
				"<option value='Equip_1_22_7_4'>22级：数字指南针 </option>",
				"<option value='Equip_1_22_8_4'>22级：勇士勋章</option>",
				"<option value='Equip_1_24_1_5'>24级：突击步枪</option>",
				"<option value='Equip_1_24_2_5'>24级：迷彩装</option>",
				"<option value='Equip_1_25_3_5'>25级：钢盔</option>",
				"<option value='Equip_1_25_4_5'>25级：防滑手套</option>",
				"<option value='Equip_1_26_5_5'>26级：军靴</option>",
				"<option value='Equip_1_26_6_5'>26级：护目镜</option>",
				"<option value='Equip_1_27_7_5'>27级：数字指南针 </option>",
				"<option value='Equip_1_27_8_5'>27级：勇士勋章</option>",
				"<option value='Equip_2_4_1_1'>4级：冲锋枪</option>",
				"<option value='Equip_2_4_2_1'>4级：冲锋衣</option>",
				"<option value='Equip_2_5_3_1'>5级：战斗头盔</option>",
				"<option value='Equip_2_5_4_1'>5级：照明灯</option>",
				"<option value='Equip_2_6_5_1'>6级：战斗靴</option>",
				"<option value='Equip_2_6_6_1'>6级：运动防护镜</option>",
				"<option value='Equip_2_7_7_1'>7级：电子对讲机</option>",
				"<option value='Equip_2_7_8_1'>7级：铜星勋章</option>",
				"<option value='Equip_2_9_1_2'>9级：冲锋枪</option>",
				"<option value='Equip_2_9_2_2'>9级：冲锋衣</option>",
				"<option value='Equip_2_10_3_2'>10级：战斗头盔</option>",
				"<option value='Equip_2_10_4_2'>10级：照明灯</option>",
				"<option value='Equip_2_11_5_2'>11级：战斗靴</option>",
				"<option value='Equip_2_11_6_2'>11级：运动防护镜</option>",
				"<option value='Equip_2_12_7_2'>12级：电子对讲机</option>",
				"<option value='Equip_2_12_8_2'>12级：铜星勋章</option>",
				"<option value='Equip_2_14_1_3'>14级：冲锋枪</option>",
				"<option value='Equip_2_14_2_3'>14级：冲锋衣</option>",
				"<option value='Equip_2_15_3_3'>15级：战斗头盔</option>",
				"<option value='Equip_2_15_4_3'>15级：照明灯</option>",
				"<option value='Equip_2_16_5_3'>16级：战斗靴</option>",
				"<option value='Equip_2_16_6_3'>16级：运动防护镜</option>",
				"<option value='Equip_2_17_7_3'>17级：电子对讲机</option>",
				"<option value='Equip_2_17_8_3'>17级：铜星勋章</option>",
				"<option value='Equip_2_19_1_4'>19级：冲锋枪</option>",
				"<option value='Equip_2_19_2_4'>19级：冲锋衣</option>",
				"<option value='Equip_2_20_3_4'>20级：战斗头盔</option>",
				"<option value='Equip_2_20_4_4'>20级：照明灯</option>",
				"<option value='Equip_2_21_5_4'>21级：战斗靴</option>",
				"<option value='Equip_2_21_6_4'>21级：运动防护镜</option>",
				"<option value='Equip_2_22_7_4'>22级：电子对讲机</option>",
				"<option value='Equip_2_22_8_4'>22级：铜星勋章</option>",
				"<option value='Equip_2_24_1_5'>24级：冲锋枪</option>",
				"<option value='Equip_2_24_2_5'>24级：冲锋衣</option>",
				"<option value='Equip_2_25_3_5'>25级：战斗头盔</option>",
				"<option value='Equip_2_25_4_5'>25级：照明灯</option>",
				"<option value='Equip_2_26_5_5'>26级：战斗靴</option>",
				"<option value='Equip_2_26_6_5'>26级：运动防护镜</option>",
				"<option value='Equip_2_27_7_5'>27级：电子对讲机</option>",
				"<option value='Equip_2_27_8_5'>27级：铜星勋章</option>",
				"<option value='Equip_3_4_1_1'>4级：狙击步枪</option>",
				"<option value='Equip_3_4_2_1'>4级：作战服</option>",
				"<option value='Equip_3_5_3_1'>5级：防弹头盔</option>",
				"<option value='Equip_3_5_4_1'>5级：激光测距仪</option>",
				"<option value='Equip_3_6_5_1'>6级：山地战斗靴</option>",
				"<option value='Equip_3_6_6_1'>6级：夜视眼镜</option>",
				"<option value='Equip_3_7_7_1'>7级：便携式雷达</option>",
				"<option value='Equip_3_7_8_1'>7级：银星勋章</option>",
				"<option value='Equip_3_9_1_2'>9级：狙击步枪</option>",
				"<option value='Equip_3_9_2_2'>9级：作战服</option>",
				"<option value='Equip_3_10_3_2'>10级：防弹头盔</option>",
				"<option value='Equip_3_10_4_2'>10级：激光测距仪</option>",
				"<option value='Equip_3_11_5_2'>11级：山地战斗靴</option>",
				"<option value='Equip_3_11_6_2'>11级：夜视眼镜</option>",
				"<option value='Equip_3_12_7_2'>12级：便携式雷达</option>",
				"<option value='Equip_3_12_8_2'>12级：银星勋章</option>",
				"<option value='Equip_3_14_1_3'>14级：狙击步枪</option>",
				"<option value='Equip_3_14_2_3'>14级：作战服</option>",
				"<option value='Equip_3_15_3_3'>15级：防弹头盔</option>",
				"<option value='Equip_3_15_4_3'>15级：激光测距仪</option>",
				"<option value='Equip_3_16_5_3'>16级：山地战斗靴</option>",
				"<option value='Equip_3_16_6_3'>16级：夜视眼镜</option>",
				"<option value='Equip_3_17_7_3'>17级：便携式雷达</option>",
				"<option value='Equip_3_17_8_3'>17级：银星勋章</option>",
				"<option value='Equip_3_19_1_4'>19级：狙击步枪</option>",
				"<option value='Equip_3_19_2_4'>19级：作战服</option>",
				"<option value='Equip_3_20_3_4'>20级：防弹头盔</option>",
				"<option value='Equip_3_20_4_4'>20级：激光测距仪</option>",
				"<option value='Equip_3_21_5_4'>21级：山地战斗靴</option>",
				"<option value='Equip_3_21_6_4'>21级：夜视眼镜</option>",
				"<option value='Equip_3_22_7_4'>22级：便携式雷达</option>",
				"<option value='Equip_3_22_8_4'>22级：银星勋章</option>",
				"<option value='Equip_3_24_1_5'>24级：狙击步枪</option>",
				"<option value='Equip_3_24_2_5'>24级：作战服</option>",
				"<option value='Equip_3_25_3_5'>25级：防弹头盔</option>",
				"<option value='Equip_3_25_4_5'>25级：激光测距仪</option>",
				"<option value='Equip_3_26_5_5'>26级：山地战斗靴</option>",
				"<option value='Equip_3_26_6_5'>26级：夜视眼镜</option>",
				"<option value='Equip_3_27_7_5'>27级：便携式雷达</option>",
				"<option value='Equip_3_27_8_5'>27级：银星勋章</option>",
				"<option value='Equip_4_4_1_1'>4级：霰弹枪</option>",
				"<option value='Equip_4_4_2_1'>4级：防弹背心</option>",
				"<option value='Equip_4_5_3_1'>5级：防爆头盔</option>",
				"<option value='Equip_4_5_4_1'>5级：激光定位器</option>",
				"<option value='Equip_4_6_5_1'>6级：雪地战斗靴</option>",
				"<option value='Equip_4_6_6_1'>6级：图像增强器 </option>",
				"<option value='Equip_4_7_7_1'>7级：卫星导航仪</option>",
				"<option value='Equip_4_7_8_1'>7级：金星勋章</option>",
				"<option value='Equip_4_9_1_2'>9级：霰弹枪</option>",
				"<option value='Equip_4_9_2_2'>9级：防弹背心</option>",
				"<option value='Equip_4_10_3_2'>10级：防爆头盔</option>",
				"<option value='Equip_4_10_4_2'>10级：激光定位器</option>",
				"<option value='Equip_4_11_5_2'>11级：雪地战斗靴</option>",
				"<option value='Equip_4_11_6_2'>11级：图像增强器 </option>",
				"<option value='Equip_4_12_7_2'>12级：卫星导航仪</option>",
				"<option value='Equip_4_12_8_2'>12级：金星勋章</option>",
				"<option value='Equip_4_14_1_3'>14级：霰弹枪</option>",
				"<option value='Equip_4_14_2_3'>14级：防弹背心</option>",
				"<option value='Equip_4_15_3_3'>15级：防爆头盔</option>",
				"<option value='Equip_4_15_4_3'>15级：激光定位器</option>",
				"<option value='Equip_4_16_5_3'>16级：雪地战斗靴</option>",
				"<option value='Equip_4_16_6_3'>16级：图像增强器 </option>",
				"<option value='Equip_4_17_7_3'>17级：卫星导航仪</option>",
				"<option value='Equip_4_17_8_3'>17级：金星勋章</option>",
				"<option value='Equip_4_19_1_4'>19级：霰弹枪</option>",
				"<option value='Equip_4_19_2_4'>19级：防弹背心</option>",
				"<option value='Equip_4_20_3_4'>20级：防爆头盔</option>",
				"<option value='Equip_4_20_4_4'>20级：激光定位器</option>",
				"<option value='Equip_4_21_5_4'>21级：雪地战斗靴</option>",
				"<option value='Equip_4_21_6_4'>21级：图像增强器 </option>",
				"<option value='Equip_4_22_7_4'>22级：卫星导航仪</option>",
				"<option value='Equip_4_22_8_4'>22级：金星勋章</option>",
				"<option value='Equip_4_24_1_5'>24级：霰弹枪</option>",
				"<option value='Equip_4_24_2_5'>24级：防弹背心</option>",
				"<option value='Equip_4_25_3_5'>25级：防爆头盔</option>",
				"<option value='Equip_4_25_4_5'>25级：激光定位器</option>",
				"<option value='Equip_4_26_5_5'>26级：雪地战斗靴</option>",
				"<option value='Equip_4_26_6_5'>26级：图像增强器 </option>",
				"<option value='Equip_4_27_7_5'>27级：卫星导航仪</option>",
				"<option value='Equip_4_27_8_5'>27级：金星勋章</option>",
				"<option value='Equip_5_4_1_1'>4级：榴弹发射器</option>",
				"<option value='Equip_5_4_2_1'>4级：防弹衣</option>",
				"<option value='Equip_5_5_3_1'>5级：多功能头盔</option>",
				"<option value='Equip_5_5_4_1'>5级：激光识别器</option>",
				"<option value='Equip_5_6_5_1'>6级：防寒战斗靴</option>",
				"<option value='Equip_5_6_6_1'>6级：热成像瞄准镜</option>",
				"<option value='Equip_5_7_7_1'>7级：卫星通信仪</option>",
				"<option value='Equip_5_7_8_1'>7级：荣誉勋章</option>",
				"<option value='Equip_5_9_1_2'>9级：榴弹发射器</option>",
				"<option value='Equip_5_9_2_2'>9级：防弹衣</option>",
				"<option value='Equip_5_10_3_2'>10级：多功能头盔</option>",
				"<option value='Equip_5_10_4_2'>10级：激光识别器</option>",
				"<option value='Equip_5_11_5_2'>11级：防寒战斗靴</option>",
				"<option value='Equip_5_11_6_2'>11级：热成像瞄准镜</option>",
				"<option value='Equip_5_12_7_2'>12级：卫星通信仪</option>",
				"<option value='Equip_5_12_8_2'>12级：荣誉勋章</option>",
				"<option value='Equip_5_14_1_3'>14级：榴弹发射器</option>",
				"<option value='Equip_5_14_2_3'>14级：防弹衣</option>",
				"<option value='Equip_5_15_3_3'>15级：多功能头盔</option>",
				"<option value='Equip_5_15_4_3'>15级：激光识别器</option>",
				"<option value='Equip_5_16_5_3'>16级：防寒战斗靴</option>",
				"<option value='Equip_5_16_6_3'>16级：热成像瞄准镜</option>",
				"<option value='Equip_5_17_7_3'>17级：卫星通信仪</option>",
				"<option value='Equip_5_17_8_3'>17级：荣誉勋章</option>",
				"<option value='Equip_5_19_1_4'>19级：榴弹发射器</option>",
				"<option value='Equip_5_19_2_4'>19级：防弹衣</option>",
				"<option value='Equip_5_20_3_4'>20级：多功能头盔</option>",
				"<option value='Equip_5_20_4_4'>20级：激光识别器</option>",
				"<option value='Equip_5_21_5_4'>21级：防寒战斗靴</option>",
				"<option value='Equip_5_21_6_4'>21级：热成像瞄准镜</option>",
				"<option value='Equip_5_22_7_4'>22级：卫星通信仪</option>",
				"<option value='Equip_5_22_8_4'>22级：荣誉勋章</option>",
				"<option value='Equip_5_24_1_5'>24级：榴弹发射器</option>",
				"<option value='Equip_5_24_2_5'>24级：防弹衣</option>",
				"<option value='Equip_5_25_3_5'>25级：多功能头盔</option>",
				"<option value='Equip_5_25_4_5'>25级：激光识别器</option>",
				"<option value='Equip_5_26_5_5'>26级：防寒战斗靴</option>",
				"<option value='Equip_5_26_6_5'>26级：热成像瞄准镜</option>",
				"<option value='Equip_5_27_7_5'>27级：卫星通信仪</option>",
				"<option value='Equip_5_27_8_5'>27级：荣誉勋章</option>",
	        ];
var stones = [
				"<option value='all_stones'>全部材料</option>",
				"<option value='material1'>1级超能合金</option>",
				"<option value='material2'>2级超能合金</option>",
				"<option value='material3'>3级超能合金</option>",
				"<option value='material4'>4级超能合金</option>",
				"<option value='material5'>5级超能合金</option>",
				"<option value='material6'>1级磁能核心</option>",
				"<option value='material7'>2级磁能核心</option>",
				"<option value='material8'>3级磁能核心</option>",
				"<option value='material9'>4级磁能核心</option>",
				"<option value='material10'>5级磁能核心</option>",
				"<option value='material11'>1级电能核心</option>",
				"<option value='material12'>2级电能核心</option>",
				"<option value='material13'>3级电能核心</option>",
				"<option value='material14'>4级电能核心</option>",
				"<option value='material15'>5级电能核心</option>",
				"<option value='material16'>1级反物质外壳</option>",
				"<option value='material17'>2级反物质外壳</option>",
				"<option value='material18'>3级反物质外壳</option>",
				"<option value='material19'>4级反物质外壳</option>",
				"<option value='material20'>5级反物质外壳</option>",
				"<option value='material21'>1级反重力外壳</option>",
				"<option value='material22'>2级反重力外壳</option>",
				"<option value='material23'>3级反重力外壳</option>",
				"<option value='material24'>4级反重力外壳</option>",
				"<option value='material25'>5级反重力外壳</option>",
				"<option value='material26'>1级高能材料</option>",
				"<option value='material27'>2级高能材料</option>",
				"<option value='material28'>3级高能材料</option>",
				"<option value='material29'>4级高能材料</option>",
				"<option value='material30'>5级高能材料</option>",
				"<option value='material31'>1级光能晶体</option>",
				"<option value='material32'>2级光能晶体</option>",
				"<option value='material33'>3级光能晶体</option>",
				"<option value='material34'>4级光能晶体</option>",
				"<option value='material35'>5级光能晶体</option>",
				"<option value='material36'>1级核能核心</option>",
				"<option value='material37'>2级核能核心</option>",
				"<option value='material38'>3级核能核心</option>",
				"<option value='material39'>4级核能核心</option>",
				"<option value='material40'>5级核能核心</option>",
				"<option value='material41'>1级氪金外壳</option>",
				"<option value='material42'>2级氪金外壳</option>",
				"<option value='material43'>3级氪金外壳</option>",
				"<option value='material44'>4级氪金外壳</option>",
				"<option value='material45'>5级氪金外壳</option>",
				"<option value='material46'>1级热能核心</option>",
				"<option value='material47'>2级热能核心</option>",
				"<option value='material48'>3级热能核心</option>",
				"<option value='material49'>4级热能核心</option>",
				"<option value='material50'>5级热能核心</option>",
				"<option value='material51'>1级碳化硅晶体</option>",
				"<option value='material52'>2级碳化硅晶体</option>",
				"<option value='material53'>3级碳化硅晶体</option>",
				"<option value='material54'>4级碳化硅晶体</option>",
				"<option value='material55'>5级碳化硅晶体</option>",
				"<option value='material56'>1级液态超金属</option>",
				"<option value='material57'>2级液态超金属</option>",
				"<option value='material58'>3级液态超金属</option>",
				"<option value='material59'>4级液态超金属</option>",
				"<option value='material60'>5级液态超金属</option>",
				"<option value='material61'>1级金属晶体</option>",
				"<option value='material62'>2级金属晶体</option>",
				"<option value='material63'>3级金属晶体</option>",
				"<option value='material64'>4级金属晶体</option>",
				"<option value='material65'>5级金属晶体</option>",
				"<option value='material66'>1级钛钢</option>",
				"<option value='material67'>2级钛钢</option>",
				"<option value='material68'>3级钛钢</option>",
				"<option value='material69'>4级钛钢</option>",
				"<option value='material70'>5级钛钢</option>",
				"<option value='material71'>1级铝合金</option>",
				"<option value='material72'>2级铝合金</option>",
				"<option value='material73'>3级铝合金</option>",
				"<option value='material74'>4级铝合金</option>",
				"<option value='material75'>5级铝合金</option>",
				"<option value='drawing101'>普通武器设计图</option>",
				"<option value='drawing102'>精良武器设计图</option>",
				"<option value='drawing103'>罕见武器设计图</option>",
				"<option value='drawing104'>稀有武器设计图</option>",
				"<option value='drawing105'>专家武器设计图</option>",
				"<option value='drawing201'>普通服装设计图</option>",
				"<option value='drawing202'>精良服装设计图</option>",
				"<option value='drawing203'>罕见服装设计图</option>",
				"<option value='drawing204'>稀有服装设计图</option>",
				"<option value='drawing205'>专家服装设计图</option>",
				"<option value='drawing301'>普通头部设计图</option>",
				"<option value='drawing302'>精良头部设计图</option>",
				"<option value='drawing303'>罕见头部设计图</option>",
				"<option value='drawing304'>稀有头部设计图</option>",
				"<option value='drawing305'>专家头部设计图</option>",
				"<option value='drawing401'>普通手部设计图</option>",
				"<option value='drawing402'>精良手部设计图</option>",
				"<option value='drawing403'>罕见手部设计图</option>",
				"<option value='drawing404'>稀有手部设计图</option>",
				"<option value='drawing405'>专家手部设计图</option>",
				"<option value='drawing501'>普通脚部设计图</option>",
				"<option value='drawing502'>精良脚部设计图</option>",
				"<option value='drawing503'>罕见脚部设计图</option>",
				"<option value='drawing504'>稀有脚部设计图</option>",
				"<option value='drawing505'>专家脚部设计图</option>",
				"<option value='drawing601'>普通眼部设计图</option>",
				"<option value='drawing602'>精良眼部设计图</option>",
				"<option value='drawing603'>罕见眼部设计图</option>",
				"<option value='drawing604'>稀有眼部设计图</option>",
				"<option value='drawing605'>专家眼部设计图</option>",
				"<option value='drawing701'>普通饰品设计图</option>",
				"<option value='drawing702'>精良饰品设计图</option>",
				"<option value='drawing703'>罕见饰品设计图</option>",
				"<option value='drawing704'>稀有饰品设计图</option>",
				"<option value='drawing705'>专家饰品设计图</option>",
				"<option value='drawing801'>普通勋章设计图</option>",
				"<option value='drawing802'>精良勋章设计图</option>",
				"<option value='drawing803'>罕见勋章设计图</option>",
				"<option value='drawing804'>稀有勋章设计图</option>",
				"<option value='drawing805'>专家勋章设计图</option>"
	        ];
var reses = [
                "<option value='food'>粮   食</option>",
                "<option value='metal'>金  属</option>",
                "<option value='oil'>石  油</option>",
                "<option value='alloy'>钛合金</option>",
                "<option value='krypton'>氪晶</option>",
				"<option value='copper'>转盘银币</option>",
				"<option value='gem'>转盘金币</option>",
				"<option value='silver'>银币</option>",
				"<option value='userexp'>玩家经验</option>",
				"<option value='stamina'>个人体力</option>",
				"<option value='allianceContr'>联盟积分</option>",
				"<option value='persContr'>联盟个人贡献度</option>"
	        ];
var levels = [
    //0-3
    ["<option value='00'>00</option>","<option value='01'>01</option>",
    "<option value='02'>02</option>","<option value='03'>03</option>" ],
    //0-0
    ["<option value='00'>00</option>"],
    //1-5
    ["<option value='01'>01</option>","<option value='02'>02</option>",
    "<option value='03'>03</option>","<option value='04'>04</option>",
    "<option value='05'>05</option>"
    ],
    //1-10
    ["<option value='01'>01</option>","<option value='02'>02</option>",
    "<option value='03'>03</option>","<option value='04'>04</option>",
    "<option value='05'>05</option>","<option value='06'>06</option>",
    "<option value='07'>07</option>","<option value='08'>08</option>",
    "<option value='09'>09</option>","<option value='10'>10</option>"
    ],
    //1-15
    ["<option value='01'>01</option>","<option value='02'>02</option>",
    "<option value='03'>03</option>","<option value='04'>04</option>",
    "<option value='05'>05</option>","<option value='06'>06</option>",
    "<option value='07'>07</option>","<option value='08'>08</option>",
    "<option value='09'>09</option>","<option value='10'>10</option>",
    "<option value='11'>11</option>","<option value='12'>12</option>",
    "<option value='13'>13</option>","<option value='14'>14</option>",
    "<option value='15'>15</option>"
    ],
    []//0-0
];
var armys = [
                "<option grade='5' value='allTroops'>所有部队</option>",
                "<option grade='5' value='allHooks'>所有陷阱</option>",
			    "<option grade='0' value='conscript'>动员兵</option>",
			    "<option grade='0' value='solider'>美国大兵</option>",
				"<option grade='1' value='teslaTrooper'>磁爆步兵</option>",
				"<option grade='0' value='flakTrooper'>防空步兵</option>",
				"<option grade='0' value='rocketeer'>火箭兵</option>",
				"<option grade='1' value='rocketFlight'>火箭飞行兵</option>",
				"<option grade='0' value='sniper'>狙击手</option>",
				"<option grade='0' value='desolator'>辐射工兵</option>",
				"<option grade='1' value='tanya'>谭雅</option>",
				"<option grade='0' value='terrorRobot'>恐怖机器人</option>",
				"<option grade='0' value='chaosDrone'>神经突击车</option>",
				"<option grade='1' value='teslaArmedCar'>磁爆装甲车</option>",
				"<option grade='0' value='flakCaterpillar'>防空履带车</option>",
				"<option grade='0' value='IFV'>多功能步兵车</option>",
				"<option grade='1' value='rocketV3'>V3火箭发射车</option>",
				"<option grade='0' value='antiTank'>反坦克战车</option>",
				"<option grade='0' value='SPG'>自行火炮车</option>",
				"<option grade='1' value='TD'>坦克歼击车</option>",
				"<option grade='0' value='rhino'>犀牛坦克</option>",
				"<option grade='0' value='mirage'>幻影坦克</option>",
				"<option grade='1' value='guardian'>守护者坦克</option>",
				"<option grade='0' value='grizzly'>灰熊坦克</option>",
				"<option grade='0' value='hammer'>铁锤坦克</option>",
				"<option grade='1' value='apocalypse'>天启坦克</option>",
				"<option grade='0' value='prism'>光棱坦克</option>",
				"<option grade='0' value='tesla'>磁能坦克</option>",
				"<option grade='1' value='tankKiller'>坦克杀手</option>",
				"<option grade='0' value='nightHawk'>夜鹰直升机</option>",
				"<option grade='0' value='twinBlade'>双刃直升机</option>",
				"<option grade='1' value='freeze'>冷冻直升机</option>",
				"<option grade='0' value='intruder'>入侵者</option>",
				"<option grade='0' value='peaceKeep'>维和轰炸机</option>",
				"<option grade='1' value='kirov'>基诺夫飞艇</option>",
				"<option grade='0' value='meager'>米格战斗机</option>",
				"<option grade='0' value='apollo'>阿波罗战斗机</option>",
				"<option grade='1' value='blackHawk'>黑鹰战机</option>",
				"<option grade='0' value='teslagrid'>电网(陷阱)</option>",
				"<option grade='0' value='HEMine'>高爆地雷(陷阱)</option>",
				"<option grade='0' value='AntitankMine'>反坦克地雷(陷阱)</option>",
				"<option grade='0' value='AntidefenseMissile'>防空导弹(陷阱)</option>"
	        ];
var builds = [
				"<option value='AllBuild'>所有</option>",
				"<option value='CityCenter'>司令部</option>",				
				"<option value='TechCenter'>科技中心</option>",	
			    "<option value='CommandPost'>指挥所</option>",					
				"<option value='SoldiersCamp'>兵营</option>",
				"<option value='TankFact'>坦克工厂</option>",
				"<option value='WarFact'>战车工厂</option>",
				"<option value='AirCom'>空指部</option>",
				"<option value='MilitaryFact'>军工厂</option>",				
				"<option value='PowerPlant'>发电厂</option>",				
				"<option value='Smelter'>冶炼厂</option>",
				"<option value='FoodFact'>食品厂</option>",
                "<option value='Hospital'>医 院</option>",
				"<option value='Repairer'>维修厂</option>",	
				"<option value='Radar'>雷 达</option>",
				"<option value='Fence'>围墙</option>",
				"<option value='MilitarySchool'>军校</option>",
				"<option value='LogisticsCenter'>仓库</option>",
				"<option value='GrandeCannon'>巨 炮</option>",
			    "<option value='LaserTower'>光棱塔</option>",
				"<option value='TeslaCoil'>磁暴线圈</option>",				
				"<option value='Refinery'>炼油厂</option>",
				"<option value='TitaniumPlant'>合金厂</option>",	
			    "<option value='Embassy'>大使馆</option>",		
				"<option value='TradeCenter'>贸易中心</option>",
				"<option value='WarLobby'>战争大厅</option>",
				"<option value='NuclearReactor'>核子反应炉</option>",
				"<option value='EquipLab'>装备实验室</option>"
	        ];	        
	       
