delete from users where id > 1;
delete from accountapply;
delete from deal;
delete from deal_order;
delete from deal_revert;
delete from email;
delete from friend;
delete from message;
delete from timeline;
delete from brokers;
delete from ubs;